# Example 3
#
# Single box with VirtualBox provider and Puppet provisioning.
#

Vagrant.configure("2") do |config|
  config.vm.box = "generic/centos6"
# config.vm.box = "centos/6"
  config.vm.hostname = "centos6.box"
#  config.vm.network :private_network, ip: "192.168.0.42"

  config.vm.provider :virtualbox do |vb|
    vb.customize [
      "modifyvm", :id,
      "--cpuexecutioncap", "50",
      "--memory", "256",
    ]
  end
  
#  config.ssh.username = 'root'
#  config.ssh.password = 'vagrant'
#  config.ssh.insert_key = 'true'  
  
#  config.vm.provision "shell", inline: <<-SHELL
#    yum install -y puppet
#  SHELL
  
#  config.vm.provision :puppet do |puppet|
#    puppet.manifests_path = "puppet/manifests"
#    puppet.manifest_file = "site.pp"
#    puppet.module_path = "puppet/modules"
#  end
end
